OCAMLC=ocamlc
OCAMLDEP=ocamldep.opt

JS_DIR=$(ROOT)/js_of_ocaml
TOPLEVEL_DIR=$(ROOT)/toplevel
OCAMLNUM_DIR=$(ROOT)/ocaml-num
TUTORIAL_DIR=$(ROOT)/tutorial
TOPLEVELLIB_DIR=$(ROOT)/toplevellib
CMICOMP_DIR=$(ROOT)/cmicomp
OCPJSLIB_DIR=$(ROOT)/ocp-jslib
