TOPLEVELLIB_CMAS=\
        $(TOPLEVELLIB_DIR)/ocamlcommon.cma \
        $(TOPLEVELLIB_DIR)/ocamlbytecomp.cma \
        $(TOPLEVELLIB_DIR)/ocamltoplevel.cma \

INCLUDE_TOPLEVELLIB= -I $(TOPLEVELLIB_DIR)/
TOPLEVELLIB=$(TOPLEVELLIB_DIR)/
CMICOMP_FLAGS=compress
