all:
	echo Use this Makefile to update this directory from a patched OCaml toplevel

update:
	cp `ocamlc -where`/compiler-libs/ocamlbytecomp.cma .
	cp `ocamlc -where`/compiler-libs/ocamlcommon.cma .
	cp `ocamlc -where`/compiler-libs/ocamltoplevel.cma .
	cp `ocamlc -where`/compiler-libs/topdirs.cmi .
	cp `ocamlc -where`/compiler-libs/toploop.cmi .
	cp `ocamlc -where`/compiler-libs/outcometree.cmi .
	cp `ocamlc -where`/compiler-libs/clflags.cmi .
