ROOT=..
TRYOCAML_NAME=try-js_of_ocaml
LESSON_SET=$(ROOT)/js_of_ocaml-lessons

TRYOCAML_EXTRA_CMIS=
TRYOCAML_EXTRA_CMAS=
TRYOCAML_EXTRA_MODULES= \
  css \
  dom \
  dom_events \
  dom_html \
  event_arrows \
  file \
  firebug \
  form \
  js \
  json \
  deriving_Json \
  lwt_js \
  regexp \
  url \
  xmlHttpRequest \

include $(ROOT)/Makefile.config
include $(ROOT)/Makefile.tryocaml
include $(ROOT)/Makefile.rules
